### ISSUE TITLE
Only support one thermal sensor per PSU

### ISSUE THREAD

**Issue by nicwu-cel** [opencomputeproject/HWMgmt-DeviceMgr-PSME#1]
Hi Developers,

I found that a PSU in the code can only have one temperature sensor, and the final name format is 'PSU 1 Thermal Sensor 1 Temperature' or 'PSU 2 Thermal Sensor 1 Temperature'. But I found some PSUs come with two temperature sensors. This caused the name that should have been 'PSU 1 Thermal Sensor 2 Temperature' to become ''PSU 2 Thermal Sensor 1 Temperature''. This is clearly misplaced. Another problem caused by this is because the total number of temperature sensors in my PSU is 4, and by default a PSU only has one sensor, so I can only display 2 temperatures.
And my question is, is this problem known and by design, and if so, should I modify 'onlpd' to show it as a PSU with only one sensor or modify the PSME configuration file to fix it.

Looking forward to hearing from you soon.

**Comment by jcleung5549** [comment]
The limited support was implement since the Redfish schema were evolving quickly during the era of  Intel's RackScale when PSME was developed.  In the Redfish Schema 2020.4, the ./Chassis/{id}/Power resource was deprecated for ./Chassis/{id}/PowerSubsystem resource.  In the new model, the PSU's are a collection resource subordinate to Chassis - ./Chassis/{id}/PowerSubsystem/PowerSupplies/{id}/Metrics.  In the Metrics resource, the TemperatureCelsius property represents "The temperature (C) for this power supply."

This means that PSME's PSUs model is probably based on the older model.  Feel free to make the changes to 'onlpd' to support your use case.

**Comment by jcleung5549** [comment]
Note - the subproject resources are focused on adding Redfish support to Device Manager's northbound interface.

**Comment by nicwu-cel** [comment]
Does it mean any further development in this outdated repository is not recommended because the subproject is on the road?

**Comment by jcleung5549** [comment]
Not at all, I wanted to set the expectation of how quickly to expect a response.  We contributed this repository produced a SW agent which ran in-band on ONL/ONIE and support the OCP Baseline profile.  When we built the Device Manager portion, we found build problems which the contributors helped resolve. Unfortunately, the contributors have moved on, so that won't be available to help.

**Comment by nicwu-cel** [comment]
Would it be OK if we add some changes to this PSME code to support one PSU coming with more than 1 thermal sensor?

**Comment by jcleung5549** [comment]
I would say sure.  The official approval will come at the next Device-Mgr meeting (Dec 13). Then there will be an approved issue  to which to link the pull request.
